// Mia Chat — Shared across all pages
function toggleMia(){const b=document.getElementById("mia-body"),l=document.getElementById("mia-toggle-label");if(b.classList.contains("open")){b.classList.remove("open");l.textContent="\u2193"}else{b.classList.add("open");l.textContent="\u2191";document.getElementById("mia-input").focus()}}
const MIA_R={
"fördermittel":["11 F\u00f6rderprogramme f\u00fcr Glash\u00fctte identifiziert. Top 3: Kulturraum (Frist 31.08.), Glasfaser-Bundesf\u00f6rderung, FR-Regio."],
"windkraft":["Windkraft: 46% der B\u00fcrgerdiskussionen, 78% negativ. 342 Posts analysiert."],
"digital":["Glash\u00fctte: 1/6 digitale Services vs. Dippoldiswalde 5/6. Gleicher Anbieter, 2-4 Wochen Umsetzung."],
"uhren":["Luxusuhrenmarkt stabil (+3.2%). Alle Glash\u00fctter Manufakturen im Luxussegment."],
"projektvorschlag":["Basierend auf Ihrem Profil:<br><br><strong>1. Tourismuskonzept Uhrenstadt</strong> (3 Credits)<br><strong>2. Fachkr\u00e4fte-Kampagne</strong> (2 Credits)<br><strong>3. Energie-Audit Kommune</strong> (2 Credits)"],
"termin":["Ich verbinde Sie mit Florian Ziesche.<br><a href='https://calendly.com/florian-ainaryventures/15-minutes-chat' style='color:var(--accent);font-weight:600;font-size:8pt' target='_blank'>30-Minuten-Termin buchen \u2192</a>"],
"danke":["Gern geschehen. Ich bin hier wenn Sie Fragen haben."]
};
function miaFind(t){t=t.toLowerCase();if(t.includes("f\u00f6rder")||t.includes("geld")||t.includes("antrag"))return MIA_R["fördermittel"];if(t.includes("wind"))return MIA_R["windkraft"];if(t.includes("digital")||t.includes("online"))return MIA_R["digital"];if(t.includes("uhr")||t.includes("lange")||t.includes("nomos"))return MIA_R["uhren"];if(t.includes("vorschlag")||t.includes("empfiehl"))return MIA_R["projektvorschlag"];if(t.includes("termin")||t.includes("florian"))return MIA_R["termin"];if(t.includes("danke")||t.includes("super"))return MIA_R["danke"];return["Ich kann zu <strong>F\u00f6rdermitteln</strong>, <strong>Digitalisierung</strong>, <strong>B\u00fcrgerstimmung</strong> und <strong>Uhrenindustrie</strong> Auskunft geben. Oder sagen Sie <strong>\u201eProjektvorschlag\u201c</strong>."];}
function miaAddMsg(t,u){const m=document.getElementById("mia-messages"),d=document.createElement("div");d.className="mia-msg"+(u?" user":"");if(u){d.innerHTML='<div class="mia-msg-t">'+t+"</div>";m.appendChild(d);m.scrollTop=m.scrollHeight}else{const av=document.createElement("div");av.className="mia-msg-a";av.textContent="M";const tb=document.createElement("div");tb.className="mia-msg-t";d.appendChild(av);d.appendChild(tb);m.appendChild(d);m.scrollTop=m.scrollHeight;const chars=t.split("");let i=0,buf="",inTag=false;(function tick(){if(i>=chars.length){tb.innerHTML=t;m.scrollTop=m.scrollHeight;return}buf+=chars[i];if(chars[i]==="<")inTag=true;if(chars[i]===">")inTag=false;i++;if(inTag){tick()}else{tb.innerHTML=buf;m.scrollTop=m.scrollHeight;setTimeout(tick,14+Math.random()*10)}})()}}
function sendChip(t){const b=document.getElementById("mia-body"),l=document.getElementById("mia-toggle-label");if(!b.classList.contains("open")){b.classList.add("open");l.textContent="\u2191"}miaAddMsg(t,true);setTimeout(()=>{const[r]=miaFind(t);miaAddMsg(r,false)},600+Math.random()*600)}
function sendMia(){const i=document.getElementById("mia-input"),t=i.value.trim();if(!t)return;miaAddMsg(t,true);i.value="";setTimeout(()=>{const[r]=miaFind(t);miaAddMsg(r,false)},600+Math.random()*800)}

// Auto-inject Mia HTML if #mia-slot exists
document.addEventListener("DOMContentLoaded",function(){const slot=document.getElementById("mia-slot");if(slot){slot.innerHTML='<div class="mia" id="mia"><div class="mia-header" onclick="toggleMia()"><div class="mia-av">M</div><div class="mia-greeting"><strong>Mia:</strong> Kann ich Ihnen weiterhelfen?</div><span class="mia-toggle" id="mia-toggle-label">\u2193</span></div><div class="mia-body" id="mia-body"><div class="mia-messages" id="mia-messages"><div class="mia-msg"><div class="mia-msg-a">M</div><div class="mia-msg-t">Fragen Sie mich zu <strong>F\u00f6rdermitteln</strong>, <strong>Digitalisierung</strong>, <strong>B\u00fcrgerstimmung</strong> oder <strong>Uhrenindustrie</strong>.</div></div></div><div class="mia-input-row"><input class="mia-input" id="mia-input" type="text" placeholder="Frage stellen..." onkeydown="if(event.key===\'Enter\')sendMia()"><button class="mia-send" onclick="sendMia()">Senden</button></div><div class="mia-chips"><span class="mia-chip" onclick="sendChip(\'F\u00f6rdermittel\')">F\u00f6rdermittel</span><span class="mia-chip" onclick="sendChip(\'Digitalisierung\')">Digitalisierung</span><span class="mia-chip" onclick="sendChip(\'Uhrenindustrie\')">Uhrenindustrie</span><span class="mia-chip" onclick="sendChip(\'Projektvorschlag\')">Projektvorschlag</span></div><div class="mia-badge">Mia ist eine KI-Assistentin \u00b7 Antworten basieren auf Ihren Reports</div></div></div>';}});
